# .rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'config/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
